metricbeat_configs.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

# Autodiscover allows you to detect changes in the system and spawn new modules as they happen.
metricbeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html
      hints.enabled: true

metricbeat.modules:
  - module: elasticsearch
    hosts: ["http://elasticsearch:9200"]
    period: 10s
    metricsets:
      - node
      - node_stats
    enabled: true

  - module: kafka
    hosts: ["http://kafka-broker:29092"]
    period: 10s
    metricsets:
    - partition
    - consumergroup
    enabled: true

  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "event"
      - "healthcheck"
      - "info"
      - "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

setup.dashboards:
  enabled: true

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: '[elasticsearch]'
