#metricbeat_configs.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
#    reload.enabled: false

metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "event"
      - "healthcheck"
      - "info"
      - "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  - module: postgresql
    hosts: ["postgres://db:5432?sslmode=disable"]
    metricsets:
      - database
      - bgwriter
      - activity
      - statement
    period: 10s
    enabled: true
    username: postgres
    password: postgres

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: '[elasticsearch]'
